  version : '3'
  services:
    front_end:
      container_name: front_end
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
      - "3000:3000"
      restart: always
      depends_on:
      - "customer"
      - "product"
      networks:
        - micro-dev-net

    customer:
      container_name: customer
      build:
       context: ./customer
       dockerfile: Dockerfile 
      ports:
        - "8003:8003" 
      restart: always
      env_file:
        - .env 
      networks:
        - micro-dev-net

    product:
      container_name: product
      build:
       context: ./product
       dockerfile: Dockerfile
      ports:
        - "8001:8001" 
      restart: always
      env_file:
        - .env 
      networks:
        - micro-dev-net
        
    nginx:
      container_name: nginx
      build:
        context: ./proxy
      depends_on:
      - "front_end"
      ports:
      - "80:80"
      networks:
        - micro-dev-net

  networks:
    micro-dev-net:
      external: true  