  version : '3'
  services:
    front_end:
      container_name: front_end
      image: thanhlam2k4/microservice-fe
      ports:
      - "3000:3000"
      restart: always
      depends_on:
      - "customer"
      - "product"
      networks:
        - micro-dev-net

    customer:
      container_name: customer
      image: thanhlam2k4/microservice-customer
      ports:
        - "8003:8003" 
      restart: always
      networks:
        - micro-dev-net

    product:
      container_name: product
      image: thanhlam2k4/microservice-product
      ports:
        - "8001:8001" 
      restart: always
      networks:
        - micro-dev-net
        
    nginx:
      container_name: nginx
      build:
        context: ./proxy
      depends_on:
      - "front_end"
      ports:
      - "80:80"
      networks:
        - micro-dev-net

  networks:
    micro-dev-net:
      external: true  